CREATE TABLE IF NOT EXISTS documents (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	title VARCHAR(200),
	description VARCHAR,
	document_type VARCHAR,
	spdx_relation VARCHAR(200),
	url VARCHAR,
	section VARCHAR NOT NULL,
	"offset" INTEGER NOT NULL,
	valid INTEGER NOT NULL,
	created_by_id INTEGER NOT NULL,
	edited_by_id INTEGER NOT NULL,
	status VARCHAR(30) NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	FOREIGN KEY(created_by_id) REFERENCES users (id),
	FOREIGN KEY(edited_by_id) REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS documents_history (
	row_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	id INTEGER NOT NULL,
	title VARCHAR(200),
	description VARCHAR,
	document_type VARCHAR,
	spdx_relation VARCHAR(200),
	url VARCHAR,
	section VARCHAR NOT NULL,
	"offset" INTEGER NOT NULL,
	valid INTEGER NOT NULL,
	created_by_id INTEGER NOT NULL,
	edited_by_id INTEGER NOT NULL,
	status VARCHAR(30) NOT NULL,
	version INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	FOREIGN KEY(created_by_id) REFERENCES users (id),
	FOREIGN KEY(edited_by_id) REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS document_mapping_api (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	api_id INTEGER NOT NULL,
	document_id INTEGER NOT NULL,
	section VARCHAR NOT NULL,
	"offset" INTEGER NOT NULL,
	coverage INTEGER NOT NULL,
	created_by_id INTEGER NOT NULL,
	edited_by_id INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	FOREIGN KEY(api_id) REFERENCES apis (id),
	FOREIGN KEY(document_id) REFERENCES documents (id),
	FOREIGN KEY(created_by_id) REFERENCES users (id),
	FOREIGN KEY(edited_by_id) REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS document_mapping_api_history (
	row_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	id INTEGER NOT NULL,
	api_id INTEGER NOT NULL,
	document_id INTEGER NOT NULL,
	section VARCHAR NOT NULL,
	"offset" INTEGER NOT NULL,
	coverage INTEGER NOT NULL,
	created_by_id INTEGER NOT NULL,
	edited_by_id INTEGER NOT NULL,
	version INTEGER NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,
	FOREIGN KEY(api_id) REFERENCES apis (id),
	FOREIGN KEY(document_id) REFERENCES documents (id),
	FOREIGN KEY(created_by_id) REFERENCES users (id),
	FOREIGN KEY(edited_by_id) REFERENCES users (id)
);