FROM registry.fedoraproject.org/fedora:39
USER root
RUN mkdir BASIL-API
WORKDIR /BASIL-API

# Install dependencies
RUN dnf install -y curl git jq patch \
    python3 python3-pip python3-virtualenv \
    podman rsync

COPY . .

COPY . .

RUN virtualenv penv && \
    source penv/bin/activate && \
    pip3 install --no-cache-dir -r requirements.txt

# Set the public ip in the api/api_url.py
ARG AI_PORT=8080 \
    API_URL=http://localhost \
    API_PORT=5000 \
    ADMIN_PASSWORD=admin \
    TESTING=0
ENV BASIL_ADMIN_PASSWORD=${ADMIN_PASSWORD} \
    BASIL_AI_PORT=${AI_PORT} \
    BASIL_API_URL=${API_URL} \
    BASIL_API_PORT=${API_PORT} \
    BASIL_TESTING=${TESTING}

# Create directories
RUN mkdir -p /var/tmp && \
    mkdir -p /BASIL-API/api/user-files

# Init the database and
# Write permission to db
RUN chmod a+rw /BASIL-API/db

# Apply patches
RUN patch -u /BASIL-API/penv/lib/python3.12/site-packages/tmt/steps/provision/podman.py < /BASIL-API/misc/tmt_provision_podman.patch  && \
    tmt init

EXPOSE ${BASIL_API_PORT}

WORKDIR /BASIL-API/api
CMD source /BASIL-API/penv/bin/activate && \
    gunicorn \
    --timeout 120 \
    --workers 4 \
    --threads 2 \
    --access-logfile /var/tmp/gunicorn-access.log \
    --error-logfile /var/tmp/gunicorn-error.log \
    --bind 0.0.0.0:${BASIL_API_PORT} api:app 2>&1 | tee /var/tmp/basil-api-error.log
