FROM debian:12
USER root
RUN mkdir BASIL-API
WORKDIR /BASIL-API

ARG PANDOC_TMPDIR=/tmp/pandoc/workdir

RUN apt update && apt install --assume-yes \
    curl git graphviz jq patch podman \
    python3 python3-pip python3-virtualenv \
    rsync

# Install Pandoc dependencies
RUN mkdir -p ${PANDOC_TMPDIR} \
    && chmod a+rw ${PANDOC_TMPDIR}

RUN apt install --assume-yes \
    pandoc \
    wkhtmltopdf \
    fontconfig \
    fonts-roboto \
    libxrender1 \
    libxext6 \
    libx11-6 \
    libstdc++6 \
    ca-certificates \\
    && apt clean

COPY . .

RUN virtualenv penv && \
    . penv/bin/activate && \
    pip3 install --no-cache-dir -r requirements.txt

# Set the public ip in the api/api_url.py
ARG API_PORT=5000
ARG ADMIN_PASSWORD=admin
ARG TESTING=0
ARG DB_PORT=5432
ARG DB_PASSWORD=password

ENV BASIL_ADMIN_PASSWORD=${ADMIN_PASSWORD} \
    BASIL_API_PORT=${API_PORT} \
    BASIL_TESTING=${TESTING} \
    BASIL_DB_PORT=${DB_PORT} \
    BASIL_DB_PASSWORD=${DB_PASSWORD} \
    BASIL_PANDOC_TMPDIR=${PANDOC_TMPDIR}

# Create directories
RUN mkdir -p /var/tmp && \
    mkdir -p /BASIL-API/api/user-files

# Write permission to db folder
RUN chmod a+rw /BASIL-API/db

# Apply patches and init tmt
RUN patch -u /BASIL-API/penv/lib/python3.11/site-packages/tmt/steps/provision/podman.py < /BASIL-API/misc/tmt_provision_podman.patch && \
    patch -u /BASIL-API/penv/lib/python3.11/site-packages/tmt/steps/provision/podman.py < /BASIL-API/misc/tmt_provision_podman_debian.patch && \
    patch -u /BASIL-API/penv/lib/python3.11/site-packages/tmt/package_managers/apt.py < /BASIL-API/misc/tmt_provision_podman_debian_apt.patch && \
    . /BASIL-API/penv/bin/activate && tmt init

EXPOSE ${BASIL_API_PORT}
CMD echo "BASIL_API_PORT: ${BASIL_API_PORT}" && \
    . /BASIL-API/penv/bin/activate && \
    cd api && \
    BASIL_TESTING=${BASIL_TESTING} gunicorn \
    --timeout 120 \
    --workers 4 \
    --access-logfile - \
    --error-logfile - \
    --bind 0.0.0.0:${BASIL_API_PORT} api:app
