FROM registry.fedoraproject.org/fedora:39
USER root
RUN mkdir BASIL-API
WORKDIR /BASIL-API

# Install dependencies
RUN dnf install -y curl git jq patch python3 python3-pip podman rsync

COPY . .

RUN pip3 install --no-cache-dir -r requirements.txt

# Set the public ip in the api/api_url.py
ARG API_PORT=5000
ARG ADMIN_PASSWORD=admin
ARG TESTING=0
ARG DB_PORT=5432
ARG DB_PASSWORD=password

ENV BASIL_ADMIN_PASSWORD=${ADMIN_PASSWORD} \
    BASIL_API_PORT=${API_PORT} \
    BASIL_TESTING=${TESTING} \
    BASIL_DB_PORT=${DB_PORT} \
    BASIL_DB_PASSWORD=${DB_PASSWORD}

# Create directories
RUN mkdir -p /var/tmp && \
    mkdir -p /BASIL-API/api/user-files

# Init the database and
# Write permission to db
RUN chmod a+rw /BASIL-API/db

# Apply patches
RUN set -eux; \
    TARGET=$(find / -type f -name podman.py | head -n 1); \
    [ -f "$TARGET" ] || { echo "No podman.py file found"; exit 1; }; \
    patch "$TARGET" < /BASIL-API/misc/tmt_provision_podman.patch

EXPOSE ${BASIL_API_PORT}
CMD echo "BASIL_API_PORT: ${BASIL_API_PORT}" && cd api && \
                        BASIL_TESTING=${BASIL_TESTING} gunicorn \
                        --timeout 120 \
                        --workers 4 \
                        --access-logfile - \
                        --error-logfile - \
                        --bind 0.0.0.0:${BASIL_API_PORT} api:app
