FROM debian:12
USER root
RUN mkdir BASIL-API
WORKDIR /BASIL-API
COPY api/ /BASIL-API/api
COPY db/ /BASIL-API/db
COPY examples/ /BASIL-API/examples
COPY misc/ /BASIL-API/misc
COPY requirements.txt pyproject.toml /BASIL-API/
RUN apt update 
RUN apt install --assume-yes \
    curl git patch podman \
    python3 python3-pip python3-virtualenv \
    rsync
    
RUN virtualenv penv && \
    . penv/bin/activate && \
    pip3 install --no-cache-dir -r requirements.txt

# Set the public ip in the api/api_url.py
ARG API_PORT=5000
ARG ADMIN_PASSWORD=admin
ENV BASIL_ADMIN_PASSWORD=${ADMIN_PASSWORD} BASIL_API_PORT=${API_PORT}

# Init the database and
# Write permission to db
RUN mkdir -p /var/tmp && \
    cd /BASIL-API/db/models && \
    . /BASIL-API/penv/bin/activate && \
    python3 init_db.py && \
    ls /BASIL-API/penv/lib/ && \
    chmod a+rw /BASIL-API/db

# Apply patches
RUN patch -u /BASIL-API/penv/lib/python3.11/site-packages/tmt/steps/provision/podman.py < /BASIL-API/misc/tmt_provision_podman.patch
RUN patch -u /BASIL-API/penv/lib/python3.11/site-packages/tmt/steps/provision/podman.py < /BASIL-API/misc/tmt_provision_podman_debian.patch
RUN patch -u /BASIL-API/penv/lib/python3.11/site-packages/tmt/package_managers/apt.py < /BASIL-API/misc/tmt_provision_podman_debian_apt.patch

# Init tmt
RUN . /BASIL-API/penv/bin/activate && tmt init

# Remove BASIL ADMIN PASSWORD from the environment
ENV BASIL_ADMIN_PASSWORD=

EXPOSE ${BASIL_API_PORT}
CMD echo "BASIL_API_PORT: ${BASIL_API_PORT}" && \
    . /BASIL-API/penv/bin/activate && \
    cd api && \
    gunicorn \
    --timeout 120 \
    --access-logfile /var/tmp/gunicorn-access.log \
    --error-logfile /var/tmp/gunicorn-error.log \
    --bind 0.0.0.0:${BASIL_API_PORT} api:app 2>&1 | tee /var/tmp/basil-api-error.log
