FROM registry.fedoraproject.org/fedora:39
USER root
RUN mkdir BASIL-API
WORKDIR /BASIL-API

# Install dependencies
RUN dnf install -y curl git jq patch python3 python3-pip podman rsync

COPY . .

RUN pip3 install --no-cache-dir -r requirements.txt

# Set the public ip in the api/api_url.py
ARG API_PORT=5000 \
    ADMIN_PASSWORD=admin \
    TESTING=0
ENV BASIL_ADMIN_PASSWORD=${ADMIN_PASSWORD} \
    BASIL_API_PORT=${API_PORT} \
    TESTING=${TESTING}

# Create directories
RUN mkdir -p /var/tmp && \
    mkdir -p /BASIL-API/api/user-files

# Init the database and
# Write permission to db
RUN cd /BASIL-API/db/models && \
    python3 init_db.py && \
    chmod a+rw /BASIL-API/db

# Apply patches
RUN patch -u /usr/local/lib/python3.12/site-packages/tmt/steps/provision/podman.py < /BASIL-API/misc/tmt_provision_podman.patch

# Init tmt
RUN tmt init

# Remove BASIL ADMIN PASSWORD from the environment
ENV BASIL_ADMIN_PASSWORD=

EXPOSE ${BASIL_API_PORT}
CMD echo "BASIL_API_PORT: ${BASIL_API_PORT}" && cd api && \
                       TESTING=${TESTING} gunicorn \
                       --timeout 120 \
                       --access-logfile /var/tmp/gunicorn-access.log \
                       --error-logfile /var/tmp/gunicorn-error.log \
                       --bind 0.0.0.0:${BASIL_API_PORT} api:app 2>&1 | tee /var/tmp/basil-api-error.log
