# syntax=docker/dockerfile:1

FROM fedora
USER root
RUN mkdir BASIL-API
WORKDIR /BASIL-API
COPY . /BASIL-API
RUN dnf install -y curl python3 python3-pip

RUN curl -sSLO https://pdm-project.org/install-pdm.py
RUN python3 install-pdm.py -p /pdm
RUN /pdm/bin/pdm install

# Init the database
WORKDIR /BASIL-API/db/models
RUN /pdm/bin/pdm run python3 init_db.py

# Set the public ip in the api/api_url.py
WORKDIR /BASIL-API
ARG BASIL_HOSTNAME=localhost
ARG BASIL_API_PORT=5000
RUN echo "BASIL HOSTNAME: ${BASIL_HOSTNAME}"
RUN echo "BASIL API PORT: ${BASIL_API_PORT}"
RUN sed -i "s/5000/${BASIL_API_PORT}/g" api/api_url.py
RUN sed -i "s/localhost/${BASIL_HOSTNAME}/g" api/api_url.py

# Write permission to db
RUN chmod a+rw /BASIL-API/db

CMD ["/pdm/bin/pdm", "run", "python3", "api/api.py"]
