#!/bin/sh
# Backup BASIL DB VOLUME

# Configuration
BASIL_DB_VOLUME_NAME=basil-db-vol
DESTINATION_FOLDER=/var/tmp/backup

# Backup
mkdir -p ${DESTINATION_FOLDER}
podman volume export ${BASIL_DB_VOLUME_NAME} --output ${DESTINATION_FOLDER}/${BASIL_DB_VOLUME_NAME}_$(date '+%Y%m%d_%H%M').tar